name: Build Validation

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]

jobs:
  build-validation:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3001/api
    
    - name: Build Backend
      run: |
        cd backend
        npm run build
    
    - name: Run Frontend Tests (if available)
      run: |
        cd frontend
        if [ -f "package.json" ] && grep -q '"test"' package.json; then
          npm test -- --passWithNoTests
        else
          echo "No tests found, skipping"
        fi
    
    - name: Run Backend Tests (if available)
      run: |
        cd backend
        if [ -f "package.json" ] && grep -q '"test"' package.json; then
          npm test -- --passWithNoTests
        else
          echo "No tests found, skipping"
        fi